name: Test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: moonbitlang/setup-moonbit@v1

      - name: Moon fmt check
        run: moon fmt --check

      - name: Moon info
        run: moon info

      - name: Moon check
        run: moon check

      - name: Moon test
        run: moon test
